version: "3"

services:
  web:
    build: .
    depends_on:
      - db
    volumes:
      - ./back:/back
      - ./front:/front
    ports:
      - "8000:8000"
    env_file: .env
    command: uvicorn back.main:app --host 0.0.0.0 --port 8000 --reload
  db:
    image: postgres:12.2
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
      - PGDATA=/vat/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db