version: "3"

services:
  bme280:
    build: .
    volumes:
      - .:/raspi
    env_file: .env
    command: python bme.py
  pump:
    build: .
    volumes:
      - .:/raspi
    env_file: .env
    command: python pump.py
